### ISSUE TITLE
Query > than 5000 items

### ISSUE THREAD

**Issue by FelixFuin** [gunjandatta/sprest#140] opened 2018-04-16 14:42 UTC
Hi,

How can I get more than 5000 items ? 

I'm currently using `list.Items().query({ Top: 5000, GetAllItems: true }).execute()`

Thanks in advance, great lib!

**Comment by gunjandatta** [comment] 2018-04-16 15:05
Setting the flag will trigger the request to check for paging and repeat the request until all data is returned. Refer to this [blog post](http://dattabase.com/query-5000-items-using-rest/) for additional information. If this resolves your question, please close this issue out. Otherwise, please provide error messages to help troubleshoot the issue.

**Comment by FelixFuin** [comment] 2018-04-16 15:09
Ok, thanks, now I understand the behavior. 
A composant from Andt was limiting my list to 10000 items.

Have a good day

**Comment by gunjandatta** [comment] 2018-04-16 15:18
There are limitations for querying against indexed and non-indexed fields. Take a look at the blog post for some additional info that may be helpful. Also, there is no way around configuration settings in the web application for query throttling. I'll assume you are working with default settings.

**Comment by FelixFuin** [comment] 2018-04-17 15:46
I was wrong, that was not due to a Antd composant..

I have 10700 items in a list SharePoint and I'm doing this : 
`list.Items().query({ Top: 5000, GetAllItems: true }).execute( items => {console.log(items.results.length, items.results}`

In my log, the length is 10000 but in items.results I have all my 10700 items. It's like the execute is running after 10000 items and later, the log of items.results is full.

Do you have any ideas ? thanks

**Comment by gunjandatta** [comment] 2018-04-17 21:38
I'll research this and get back to you on this. The issue is probably when I combine the arrays, the length isn't being updated.

**Comment by gunjandatta** [comment] 2018-04-18 00:58
This is def a bug. Thank you for reporting this.

**Comment by gunjandatta** [comment] 2018-04-18 01:03
Fixed in v3.8.6.

**Closed by gunjandatta** 2018-04-18 01:03 UTC
Labels: bug

**Comment by gunjandatta** [comment] 2018-04-18 12:12
I tested against a large list containing 10700 items, executing the same request. I was able to reproduce the issue, but please reopen if it's still not working.
